<a href="https://colab.research.google.com/github/JSini/tensorflow/blob/main/tensorflow_site/tutorials/customization/custom_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### Copyright 2018 The TensorFlow Authors.

In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Custom layers

We recommend using `tf.keras` as a high-level API for building neural networks. That said, most TensorFlow APIs are usable with eager execution.


In [1]:
import tensorflow as tf

In [3]:
print(tf.config.list_physical_devices('GPU'))

[]


In [2]:
tf.config.list_physical_devices('GPU')

[]

## Layers: common sets of useful operations

Most of the time when writing code for machine learning models you want to operate at a higher level of abstraction than individual operations and manipulation of individual variables.

Many machine learning models are expressible as the composition and stacking of relatively simple layers, and TensorFlow provides both a set of many common layers as well as easy ways for you to write your own application-specific layers either from scratch or as the composition of existing layers.

TensorFlow includes the full [Keras](https://keras.io) API in the tf.keras package, and the Keras layers are very useful when building your own models.


In [9]:
# In the tf.keras.layers package, layers are objects. To construct a layer,
# simply construct the object. Most layers take as a first argument the number
# of output dimensions / channels.
layer = tf.keras.layers.Dense(100)
# The number of input dimensions is often unnecessary, as it can be inferred
# the first time the layer is used, but it can be provided if you want to
# specify it manually, which is useful in some complex models.
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [4]:
dir(tf.keras.layers)

['AbstractRNNCell',
 'Activation',
 'ActivityRegularization',
 'Add',
 'AdditiveAttention',
 'AlphaDropout',
 'Attention',
 'Average',
 'AveragePooling1D',
 'AveragePooling2D',
 'AveragePooling3D',
 'AvgPool1D',
 'AvgPool2D',
 'AvgPool3D',
 'BatchNormalization',
 'Bidirectional',
 'CategoryEncoding',
 'CenterCrop',
 'Concatenate',
 'Conv1D',
 'Conv1DTranspose',
 'Conv2D',
 'Conv2DTranspose',
 'Conv3D',
 'Conv3DTranspose',
 'ConvLSTM1D',
 'ConvLSTM2D',
 'ConvLSTM3D',
 'Convolution1D',
 'Convolution1DTranspose',
 'Convolution2D',
 'Convolution2DTranspose',
 'Convolution3D',
 'Convolution3DTranspose',
 'Cropping1D',
 'Cropping2D',
 'Cropping3D',
 'Dense',
 'DenseFeatures',
 'DepthwiseConv1D',
 'DepthwiseConv2D',
 'Discretization',
 'Dot',
 'Dropout',
 'ELU',
 'EinsumDense',
 'Embedding',
 'Flatten',
 'GRU',
 'GRUCell',
 'GaussianDropout',
 'GaussianNoise',
 'GlobalAveragePooling1D',
 'GlobalAveragePooling2D',
 'GlobalAveragePooling3D',
 'GlobalAvgPool1D',
 'GlobalAvgPool2D',
 'GlobalAvgPo

In [5]:
dir(tf.keras.layers.Dense)

['_TF_MODULE_IGNORED_PROPERTIES',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_trackable',
 '_add_trackable_child',
 '_add_variable_with_custom_getter',
 '_autographed_call',
 '_cast_single_input',
 '_checkpoint_dependencies',
 '_clear_losses',
 '_compute_dtype',
 '_copy_trackable_to_cpu',
 '_dedup_weights',
 '_deferred_dependencies',
 '_delete_tracking',
 '_deserialization_dependencies',
 '_deserialize_from_proto',
 '_dtype',
 '_eager_losses',
 '_expects_mask_arg',
 '_expects_training_arg',
 '_export_to_saved_model_graph',
 '_flatten',
 '_flatten_layers',
 '_flatten_modules',
 '_functional_construction_call',
 '_

The full list of pre-existing layers can be seen in [the documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers). It includes Dense (a fully-connected layer),
Conv2D, LSTM, BatchNormalization, Dropout, and many others.

In [39]:
# To use a layer, simply call it.

layer1 = tf.keras.layers.Dense(100)
layer2 = tf.keras.layers.Dense(10, input_shape=(None, 5))


In [41]:
# zero tensor with shape 10 * 5
mytensor = tf.zeros([5, 2])
mytensor

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [42]:
# pass the tensor to Dense layer1
layer1(mytensor) # output shape 5 * 100

<tf.Tensor: shape=(5, 100), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 

In [43]:
layer2(mytensor)

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [46]:
# Layers have many useful methods. For example, you can inspect all variables
# in a layer using `layer.variables` and trainable variables using
# `layer.trainable_variables`. In this case a fully-connected layer
# will have variables for weights and biases.
layer2.variables

[<tf.Variable 'dense_15/kernel:0' shape=(2, 10) dtype=float32, numpy=
 array([[-0.4105919 ,  0.0844714 , -0.6300498 , -0.16832757,  0.43509036,
          0.7042971 ,  0.06325787, -0.65221626, -0.21891594, -0.0437668 ],
        [-0.08527792,  0.5757986 , -0.0520733 , -0.5361195 , -0.10854447,
          0.0976814 , -0.5529081 , -0.38492918, -0.23914626, -0.21397397]],
       dtype=float32)>,
 <tf.Variable 'dense_15/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [49]:
# ou can get the weights for the layer - with attribute 'weights'
layer2.weights

[<tf.Variable 'dense_15/kernel:0' shape=(2, 10) dtype=float32, numpy=
 array([[-0.4105919 ,  0.0844714 , -0.6300498 , -0.16832757,  0.43509036,
          0.7042971 ,  0.06325787, -0.65221626, -0.21891594, -0.0437668 ],
        [-0.08527792,  0.5757986 , -0.0520733 , -0.5361195 , -0.10854447,
          0.0976814 , -0.5529081 , -0.38492918, -0.23914626, -0.21397397]],
       dtype=float32)>,
 <tf.Variable 'dense_15/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [50]:
layer2.get_weights()

[array([[-0.4105919 ,  0.0844714 , -0.6300498 , -0.16832757,  0.43509036,
          0.7042971 ,  0.06325787, -0.65221626, -0.21891594, -0.0437668 ],
        [-0.08527792,  0.5757986 , -0.0520733 , -0.5361195 , -0.10854447,
          0.0976814 , -0.5529081 , -0.38492918, -0.23914626, -0.21397397]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]

In [52]:
w, b = layer2.get_weights()
print(w)
print(b)

[[-0.4105919   0.0844714  -0.6300498  -0.16832757  0.43509036  0.7042971
   0.06325787 -0.65221626 -0.21891594 -0.0437668 ]
 [-0.08527792  0.5757986  -0.0520733  -0.5361195  -0.10854447  0.0976814
  -0.5529081  -0.38492918 -0.23914626 -0.21397397]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [48]:
# The variables are also accessible through nice accessors
layer2.kernel, layer2.bias

(<tf.Variable 'dense_15/kernel:0' shape=(2, 10) dtype=float32, numpy=
 array([[-0.4105919 ,  0.0844714 , -0.6300498 , -0.16832757,  0.43509036,
          0.7042971 ,  0.06325787, -0.65221626, -0.21891594, -0.0437668 ],
        [-0.08527792,  0.5757986 , -0.0520733 , -0.5361195 , -0.10854447,
          0.0976814 , -0.5529081 , -0.38492918, -0.23914626, -0.21397397]],
       dtype=float32)>,
 <tf.Variable 'dense_15/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

## Implementing custom layers
The best way to implement your own layer is extending the tf.keras.Layer class and implementing:

1. `__init__` , where you can do all input-independent initialization
2. `build`, where you know the shapes of the input tensors and can do the rest of the initialization
3. `call`, where you do the forward computation

Note that you don't have to wait until `build` is called to create your variables, you can also create them in `__init__`. However, the advantage of creating them in `build` is that it enables late variable creation based on the shape of the inputs the layer will operate on. On the other hand, creating variables in `__init__` would mean that shapes required to create the variables will need to be explicitly specified.

In many cases, you may not know in advance the size of your inputs, and you would like to lazily create weights when that value becomes known, some time after instantiating the layer.

In the Keras API, we recommend creating layer weights in the build(self, inputs_shape) method of your layer. The __call__() method of your layer will automatically run build the first time it is called.

In [61]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs

  def build(self, input_shape):
    self.kernel = self.add_weight("kernel",
                                  shape=[int(input_shape[-1]),
                                         self.num_outputs])

  def call(self, inputs):
    return tf.matmul(inputs, self.kernel)

layer = MyDenseLayer(10)

In [62]:
_ = layer(tf.zeros([10, 5])) # Calling the layer `.builds` it.

In [84]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer_2/kernel:0']


In [77]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, units):
    super().__init__()
    self.units = units

  def build(self, input_shape):
    self.kernel = self.add_weight("kernel", shape=[int(input_shape[-1]), self.units], initializer="glorot_uniform")
    self.bias = self.add_weight("bias", shape=(self.units), initializer="zeros")

  def call(self, inputs):
    return tf.matmul(inputs, self.kernel) + self.bias

myLayer = MyDenseLayer(10)

In [78]:
inputs = tf.ones([5,2])
inputs

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [79]:
l = myLayer(inputs)

In [81]:
myLayer.get_weights()

[array([[ 0.52415925,  0.26594865, -0.29365292,  0.04650432,  0.53987724,
          0.45106465, -0.29136807, -0.34070146,  0.33632344,  0.5831441 ],
        [ 0.18702579,  0.3417428 , -0.3943775 , -0.51890624,  0.46836406,
         -0.55524474, -0.44287285, -0.33460552,  0.37632316, -0.14368892]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]

In [82]:
myLayer.kernel

<tf.Variable 'my_dense_layer_5/kernel:0' shape=(2, 10) dtype=float32, numpy=
array([[ 0.52415925,  0.26594865, -0.29365292,  0.04650432,  0.53987724,
         0.45106465, -0.29136807, -0.34070146,  0.33632344,  0.5831441 ],
       [ 0.18702579,  0.3417428 , -0.3943775 , -0.51890624,  0.46836406,
        -0.55524474, -0.44287285, -0.33460552,  0.37632316, -0.14368892]],
      dtype=float32)>

In [83]:
myLayer.trainable_variables

[<tf.Variable 'my_dense_layer_5/kernel:0' shape=(2, 10) dtype=float32, numpy=
 array([[ 0.52415925,  0.26594865, -0.29365292,  0.04650432,  0.53987724,
          0.45106465, -0.29136807, -0.34070146,  0.33632344,  0.5831441 ],
        [ 0.18702579,  0.3417428 , -0.3943775 , -0.51890624,  0.46836406,
         -0.55524474, -0.44287285, -0.33460552,  0.37632316, -0.14368892]],
       dtype=float32)>,
 <tf.Variable 'my_dense_layer_5/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [86]:
# total parameters
myLayer.count_params()

30

Overall code is easier to read and maintain if it uses standard layers whenever possible, as other readers will be familiar with the behavior of standard layers. If you want to use a layer which is not present in `tf.keras.layers`, consider filing a [github issue](http://github.com/tensorflow/tensorflow/issues/new) or, even better, sending us a pull request!

## Models: Composing layers

Many interesting layer-like things in machine learning models are implemented by composing existing layers. For example, each residual block in a resnet is a composition of convolutions, batch normalizations, and a shortcut. Layers can be nested inside other layers.

Typically you inherit from `keras.Model` when you need the model methods like: `Model.fit`,`Model.evaluate`, and `Model.save` (see [Custom Keras layers and models](https://www.tensorflow.org/guide/keras/custom_layers_and_models) for details).

One other feature provided by `keras.Model` (instead of `keras.layers.Layer`) is that in addition to tracking variables, a `keras.Model` also tracks its internal layers, making them easier to inspect.


In [94]:
# sublassing the Model class

class MyModel(tf.keras.Model):

    def __init__(self):
        super().__init__()
        self.dense1 = tf.keras.layers.Dense(8, activation='relu')
        self.dense2 = tf.keras.layers.Dense(3, activation='softmax')


    def call(self, inputs):
        x = self.dense1(inputs)
        output = self.dense2(x)

        return output

myModel = MyModel()

In [95]:
inputs = tf.zeros([1, 2, 3, 3])
inputs

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [96]:
myModel(inputs)

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0.33333334, 0.33333334, 0.33333334],
         [0.33333334, 0.33333334, 0.33333334],
         [0.33333334, 0.33333334, 0.33333334]],

        [[0.33333334, 0.33333334, 0.33333334],
         [0.33333334, 0.33333334, 0.33333334],
         [0.33333334, 0.33333334, 0.33333334]]]], dtype=float32)>

In [97]:
# now you will be able to call summary() method
myModel.summary()

Model: "my_model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_20 (Dense)            multiple                  32        
                                                                 
 dense_21 (Dense)            multiple                  27        
                                                                 
Total params: 59 (236.00 Byte)
Trainable params: 59 (236.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [98]:
myModel.layers

In [103]:
myModel.layers[0].output

AttributeError: ignored

Note we never specified the inputs shape, our model cannot infer the shapes, hence the summary displays layer output shape as 'multiple'

In [110]:
# sublassing the Model class

class MyModel(tf.keras.Model):

    def __init__(self):
        super().__init__()
        self.dense1 = tf.keras.layers.Dense(8, activation='relu')
        self.dense2 = tf.keras.layers.Dense(3, activation='softmax')


    def call(self, inputs):
        x = self.dense1(inputs)
        output = self.dense2(x)

        return output

    def build_graph(self, input_shapes):
        inputs = tf.keras.layers.Input(shape=(input_shapes[-1]))
        return tf.keras.Model(inputs=inputs, outputs=self.call(inputs))

myModel = MyModel()

In [116]:
inputs = tf.zeros([1, 2, 3, 3])
print(inputs.shape)
print()
# pass the input shape to the build_graph
myModel.build_graph(inputs.shape).summary()

(1, 2, 3, 3)

Model: "model_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_8 (InputLayer)        [(None, 3)]               0         
                                                                 
 dense_26 (Dense)            (None, 8)                 32        
                                                                 
 dense_27 (Dense)            (None, 3)                 27        
                                                                 
Total params: 59 (236.00 Byte)
Trainable params: 59 (236.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [112]:
myModel.build_graph(inputs.shape).layers

In [117]:
myModel.build_graph(inputs.shape).layers[1].output

<KerasTensor: shape=(None, 8) dtype=float32 (created by layer 'dense_26')>

In [118]:
myModel.build_graph(inputs.shape).layers[2].output

<KerasTensor: shape=(None, 3) dtype=float32 (created by layer 'dense_27')>

In [120]:
myModel.build_graph(inputs.shape).weights

[<tf.Variable 'dense_26/kernel:0' shape=(3, 8) dtype=float32, numpy=
 array([[-2.8674293e-01, -1.8390262e-01, -1.7522275e-02, -5.3554809e-01,
         -6.8168235e-01,  4.0598392e-02,  6.9031900e-01, -2.6497811e-01],
        [ 1.9411564e-01,  6.7757744e-01, -1.5296274e-01,  3.4116977e-01,
          4.4171780e-01, -7.1118814e-01,  4.6456772e-01,  4.7056645e-01],
        [ 6.8300962e-04,  4.7827858e-01, -7.1513575e-01, -2.0653486e-01,
          2.2426456e-01, -6.9350195e-01, -2.6225746e-02, -1.0362953e-01]],
       dtype=float32)>,
 <tf.Variable 'dense_26/bias:0' shape=(8,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_27/kernel:0' shape=(8, 3) dtype=float32, numpy=
 array([[-0.07659066,  0.16837448,  0.44584113],
        [-0.60261   ,  0.2903282 ,  0.13611948],
        [-0.21196842,  0.3912341 , -0.27545   ],
        [-0.70885116, -0.67849976, -0.3631094 ],
        [-0.4631995 ,  0.36276025,  0.39669532],
        [-0.068757  , -0.42505


For example here is a ResNet block:

In [ ]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters

    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training=training)

    x += input_tensor
    return tf.nn.relu(x)


block = ResnetIdentityBlock(1, [1, 2, 3])

In [ ]:
_ = block(tf.zeros([1, 2, 3, 3]))

In [ ]:
block.layers

In [ ]:
len(block.variables)

In [ ]:
block.summary()

Much of the time, however, models which compose many layers simply call one layer after the other. This can be done in very little code using `tf.keras.Sequential`:

In [ ]:
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1),
                                                    input_shape=(
                                                        None, None, 3)),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(2, 1,
                                                    padding='same'),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(3, (1, 1)),
                             tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))

In [ ]:
my_seq.summary()

# Next steps

Now you can go back to the previous notebook and adapt the linear regression example to use layers and models to be better structured.